name: Tests

# Trigger this workflow only when 'Build' completes successfully
on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  test-units:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace
        
  test-instrumentations:
    needs: test-units
    
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          components: |
            build-tools;31.0.0
            platform-tools
            emulator
            platforms;android-31
          ndk: false

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install System Image
        run: |
          sdkmanager "system-images;android-31;google_apis;x86_64"

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-31;google_apis;x86_64" --force
          emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          sleep 30

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest --no-daemon --stacktrace