name: Tests

# Trigger this workflow only when 'Build' completes successfully
on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  test-units:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace
        
  test-instrumentations:
    needs: test-units
    
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          target: default
          ndk: false

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Start emulator and run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          profile: "Pixel 2"
          emulator-options: -no-window -no-audio
          script: |
            ./gradlew connectedDebugAndroidTest --no-daemon --stacktrace