name: Android CI

on:
  push:
    branches:
      - main
      - staging
      - 'topic/**'
  pull_request:
    branches:
      - main
      - staging
      - 'topic/**'

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      
      # 1. Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK (adjust java-version if you target a different one)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Cache Gradle dependencies for speed
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Make the Gradle wrapper executable (if needed)
      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      # 5. Run the build
      - name: Compile (assembleDebug)
        run: ./gradlew assembleDebug --no-daemon --stacktrace