name: Tests

# Trigger this workflow only when 'Build' completes successfully
on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  test-units:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace
        
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace --info --console=plain

      - name: Publish test results
        if: always()                # ensure report even on failures
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests          # display name in Checks UI
          path: app/build/test-results/testDebugUnitTest  # folder containing XMLs
          reporter: junit           # format of your test‑result files
          reporter_options: |
            junit_simple_names=true # optional: simplify class names in report
