name: Enforce Branch Naming Convention

on:
  push:
    branches-ignore:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  enforce-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          echo "🔍 Checking branch name: $BRANCH_NAME"

          # Define allowed patterns for branch names:
          # - main
          # - staging
          # - topic/<lowercase-alphanum-and-dash>
          # - rollback/<lowercase-alphanum-and-dash>
          if [[ "$BRANCH_NAME" =~ ^(main|staging|topic\/[a-z0-9-]+|rollback\/[a-z0-9-]+)$ ]]; then
            echo "✅ Branch name '$BRANCH_NAME' is valid."
            exit 0
          else
            echo "❌ Invalid branch name: '$BRANCH_NAME'"
            echo "Allowed patterns are:"
            echo "  - main"
            echo "  - staging"
            echo "  - topic/<lowercase-name> (letters, numbers, dashes only)"
            echo "  - rollback/<lowercase-name> (letters, numbers, dashes only)"
            exit 1
          fi
