name: Enforce Conventions

on:
  push:
    branches-ignore:
      - main
      - staging

jobs:
  enforce-branch-name:
    name: Conventional Branches
    runs-on: ubuntu-latest
    steps:
      - name: Lint style against allowed conventions
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          echo "🔍 Validating branch: $BRANCH_NAME"
          
          if [[ "$BRANCH_NAME" =~ ^(main|staging|topic\/[a-z0-9-]+|rollback\/[a-z0-9-]+|debug\/[a-z0-9-]+)$ ]]; then
            echo "✅ Follows accepted conventions."
            exit 0
          else
            echo "❌ Invalid branch name: '$BRANCH_NAME'                  "
            echo "Allowed conventions:                                    "
            echo "  - main                                                "
            echo "  - staging                                             "
            echo "  - topic/<lowercase-name> (letters, numbers, dashes)   "
            echo "  - debug/<lowercase-name> (letters, numbers, dashes)   "
            echo "  - rollback/<lowercase-name> (letters, numbers, dashes)"
            exit 1
          fi
